theme: jekyll-theme-minimal
author_profile: true
title: [About me]
description: [I am Wiktor Owczarz (Ow-chash). This site is my digital resume.]
sidebar:
  - title: "Title"
    image: http://placehold.it/350x250
    image_alt: "image"
    text: "Some text here."
  - title: "Another Title"
    text: "More text here."
    nav: sidebar-sample


