theme: jekyll-theme-minimal
minimal_mistakes_skin: "contrast" # "air", "aqua", "default", "dark", "dirt", "neon", "mint", "plum" "sunrise"
title: [About me]
description: [I am Wiktor Owczarz (Ow-chash). This site is my digital resume.]
sidebar:
  title: "Sample Title"
  nav: sidebar-sample

